apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            env:
              - name: _JAVA_OPTIONS
                value: -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true
                  -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4
                  -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
            image: uses:jenkins-x/jx3-pipeline-catalog/tasks/maven-java11/release.yaml@versionStream
            name: ""
            resources:
              requests:
                cpu: 400m
                memory: 512Mi
            volumeMounts:
              - mountPath: /root/.m2/
                name: maven-settings
              - mountPath: /root/.gnupg
                name: release-gpg
            workingDir: /workspace/source
          steps:
            - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
              name: ""
              resources: {}
            - name: next-version
              resources: {}
            - name: jx-variables
              resources: {}
            - image: gcr.io/camunda-researchanddevelopment/cd-flow:0.0.10
              name: cdf-start-pipeline
              resources: { }
              script: |
                #!/usr/bin/env sh
                source /workspace/source/.jx/variables.sh
                export CDF_SINK=http://backend.35.204.61.61.xip.io/api/events
                cdf pipeline started --type module --module fmtok8s-c4p --project fmtok8s --id $VERSION || true
            - name: build-mvn-deploy
              resources: {}
            - name: build-container-build
              resources: {}
            - image: gcr.io/camunda-researchanddevelopment/cd-flow:0.0.10
              name: cdf-artifact-built
              resources: { }
              script: |
                #!/usr/bin/env sh
                source /workspace/source/.jx/variables.sh
                export CDF_SINK=http://backend.35.204.61.61.xip.io/api/events
                cdf artifact built --module fmtok8s-c4p --pipelineId $VERSION --project fmtok8s --id fmtok8s-c4p || true
            - name: promote-changelog
              resources: {}
            - name: promote-helm-release
              resources: {}
            - image: gcr.io/camunda-researchanddevelopment/cd-flow:0.0.10
              name: cdf-release-and-finish-pipeline
              resources: { }
              script: |
                #!/usr/bin/env sh
                source /workspace/source/.jx/variables.sh
                export CDF_SINK=http://backend.35.204.61.61.xip.io/api/events
                cdf artifact released --module fmtok8s-c4p --pipelineId $VERSION --project fmtok8s --id fmtok8s-c4p
                cdf pipeline finished --type module --module fmtok8s-c4p --project fmtok8s --id $VERSION || true
          #        - name: promote-jx-promote
          #          resources: {}
          volumes:
            - name: maven-settings
              secret:
                secretName: jenkins-maven-settings
            - name: release-gpg
              secret:
                optional: true
                secretName: jenkins-release-gpg
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
